from parser import ISASpec
from validator import ISAValidator

class VerilogEmitter:
    def __init__(self,spec,output_dir):
        self.spec = spec
        self.output_dir = output_dir


    def emit_decoder(self):
        lines = []
        lines.append("//decoder.v")
        lines.append("// Auto-generated by CUSTOM16 RTL ToolClain")
        lines.append("")
        lines.append("module decoder(")
        lines.append("     input ["+str(self.spec.opcode_bits-1)+ ":0] opcode,")
        for i,sig in enumerate(self.spec.ControlSignals):

            is_last = (i == len(self.spec.ControlSignals)-1)
            comma = "" if is_last else ","
            if sig.width > 1:
                line = "    output reg ["+str(sig.width-1)+ ":0] "+str(sig.name)+ comma
                
            elif sig.width == 1:
                line = "    output reg "+sig.name+comma
            
            lines.append(line)
        lines.append(");")
        lines.append("")
        lines.append("always @(*) begin")
        lines.append("    case (opcode)")
    
        for n in self.spec.Instructions:
            end = ";"
            lines.append("        4'b" + n.opcode + ": begin  // " + n.mnemonic)
            for index,m in enumerate(self.spec.ControlSignals):
                lines.append("          "+str(m.name)+" = "+str(m.width)+"'b"+str(n.control[m.name])+end)
            lines.append("          end")        

        lines.append("        default: begin")
        for sig in self.spec.ControlSignals:
            lines.append("            " + sig.name + " = " + str(sig.width) + "'b" + "0" * sig.width + ";")
        lines.append("        end")
        lines.append("    endcase")
        lines.append("end")
        lines.append("endmodule")
        
        output = "\n".join(lines)
        filepath = self.output_dir + "/decoder.v"
        with open(filepath, "w") as f:
         f.write(output)
        print("Generated: " + filepath)
        return filepath   
    
    def emit_testbench(self):
        lines = []
        lines.append("//tb_decoder.v")
        lines.append("module tb_decoder;")
        lines.append("reg["+str(self.spec.opcode_bits-1)+":0] opcode;")
        
        for sig in self.spec.ControlSignals:
            if sig.width > 1:
                lines.append("wire["+str(sig.width-1)+":0]"+str(sig.name)+ ";")
            else:
                lines.append("wire "+str(sig.name)+";")

        lines.append("decoder uut(")
        lines.append(".opcode(opcode),")
        for i,sig in enumerate(self.spec.ControlSignals):
            is_last = (i == len(self.spec.ControlSignals)-1)
            comma = "" if is_last else ","
            lines.append("."+str(sig.name)+"("+str(sig.name)+")"+comma)
        lines.append(");")

        lines.append("initial begin")
        lines.append('$display("Testing CUSTOM16 Decoder!");')
        end = ";"
        for instruction in self.spec.Instructions:
            lines.append("    opcode = " + str(self.spec.opcode_bits) + "'b" + instruction.opcode + "; #10;  // " + instruction.mnemonic)
            lines.append('    $display("' + instruction.mnemonic + ' : alu_op=%b reg_write=%b mem_read=%b mem_write=%b branch=%b jump=%b use_imm=%b", alu_op, reg_write, mem_read, mem_write, branch, jump, use_imm);')

        lines.append('$display("Simulation complete.");')
        
        lines.append("$finish;")
        lines.append("end")
        lines.append("endmodule")

        output = "\n".join(lines)
        filepath = self.output_dir + "/tb_decoder.v"
        with open(filepath, "w") as f:
            f.write(output)
        print("Generated: " + filepath)
        return filepath
    
    def emit_control_rom(self):
        lines = []
        lines.append("//control _rom.v")
        lines.append("module control_rom(")
        lines.append("  input["+str(self.spec.opcode_bits-1)+":0] opcode,")
        total_width = sum(sig.width for sig in self.spec.ControlSignals)
        lines.append("  output["+str(total_width-1)+":0] control_word")
        lines.append(");")
        total_bits = 2**self.spec.opcode_bits - 1
        lines.append("reg["+str(total_width-1)+":0] rom["+str(total_bits)+":0];")
        
        lines.append("initial begin")
        
        for n in self.spec.Instructions:
            control_word = "".join(n.control[sig.name] for sig in self.spec.ControlSignals)
            lines.append("        rom[" + str(self.spec.opcode_bits) + "'b" + n.opcode + "] = "+ str(total_width) + "'b" + control_word + ";  // " + n.mnemonic)                
   
        lines.append("end")
        lines.append("assign control_word = rom[opcode];")
        lines.append("endmodule")
        output = "\n".join(lines)
        filepath = self.output_dir + "/control_rom.v"
        with open(filepath, "w") as f:
         f.write(output)
        print("Generated: " + filepath)
        return filepath
    
              

if __name__ == "__main__":
    spec = ISASpec("../isa_spec.json")
    validator = ISAValidator(spec)
    errors = validator.validate()
    if errors:
        for e in errors:
            print("ERROR: " + e)
    else:
        emitter = VerilogEmitter(spec, "../generated")
        emitter.emit_decoder()
        emitter.emit_testbench()
        emitter.emit_control_rom()