from parser import ISASpec
from validator import ISAValidator

class VerilogEmitter:
    def __init__(self,spec,output_dir):
        self.spec = spec
        self.output_dir = output_dir


    def emit_decoder(self):
        lines = []
        lines.append("//decoder.v")
        lines.append("// Auto-generated by CUSTOM16 RTL ToolClain")
        lines.append("")
        lines.append("module decoder(")
        lines.append("     input ["+str(self.spec.opcode_bits-1)+ ":0] opcode,")
        for i,sig in enumerate(self.spec.ControlSignals):

            is_last = (i == len(self.spec.ControlSignals)-1)
            comma = "" if is_last else ","
            if sig.width > 1:
                line = "    output reg ["+str(sig.width-1)+ ":0] "+str(sig.name)+ comma
                
            elif sig.width == 1:
                line = "    output reg "+sig.name+comma
            
            lines.append(line)
        lines.append(");")
        lines.append("")
        lines.append("always @(*) begin")
        lines.append("    case (opcode)")
    
        for n in self.spec.Instructions:
            end = ";"
            lines.append("        4'b" + n.opcode + ": begin  // " + n.mnemonic)
            for index,m in enumerate(self.spec.ControlSignals):
                lines.append("          "+str(m.name)+" = "+str(m.width)+"'b"+str(n.control[m.name])+end)
            lines.append("          end")        

        lines.append("        default: begin")
        for sig in self.spec.ControlSignals:
            lines.append("            " + sig.name + " = " + str(sig.width) + "'b" + "0" * sig.width + ";")
        lines.append("        end")
        lines.append("    endcase")
        lines.append("end")
        lines.append("endmodule")
        
        output = "\n".join(lines)
        filepath = self.output_dir + "/decoder.v"
        with open(filepath, "w") as f:
         f.write(output)
        print("Generated: " + filepath)
        return filepath   
    

if __name__ == "__main__":
    spec = ISASpec("../isa_spec.json")
    validator = ISAValidator(spec)
    errors = validator.validate()
    if errors:
        for e in errors:
            print("ERROR: " + e)
    else:
        emitter = VerilogEmitter(spec, "../generated")
        emitter.emit_decoder()